### ISSUE TITLE
check validity of fit

### ISSUE THREAD

**Issue by andreaa93** [IKZ-Berlin/lakeshore-nomad-plugin#2]
@anfiedler is this voltage measurement correct? Or is it some error in the postprocessing?

![Screenshot from 2024-07-08 16-34-47](https://github.com/IKZ-Berlin/lakeshore-nomad-plugin/assets/95371554/30d49fed-0424-4232-91b6-819b442373c0)

**Comment by anfiedler** [comment]
> @anfiedler is this voltage measurement correct? Or is it some error in the postprocessing?
> 
> ![Screenshot from 2024-07-08 16-34-47](https://private-user-images.githubusercontent.com/95371554/346606093-30d49fed-0424-4232-91b6-819b442373c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTAwNjAsIm5iZiI6MTcyMDQ0OTc2MCwicGF0aCI6Ii85NTM3MTU1NC8zNDY2MDYwOTMtMzBkNDlmZWQtMDQyNC00MjMyLTkxYjYtODE5YjQ0MjM3M2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE0NDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTE5MmI4ZjcyMzEyNGQ2MzhhZTUzZTdhMmFjZjM5NmUwMmE0MmNhNTAyYWYyY2Y2ZWQ1Y2RhMGMzZDBhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IeeqDf6HO_eYLu8DdCTNnKRZM3GI0UI_e63VEtxR8FM)

Can you tell me the mesurement file? It could be that it is actually correct, but in that case the contacts are not ohmic and the measurement might be not reliable.

**Comment by andreaa93** [comment]
> > @anfiedler is this voltage measurement correct? Or is it some error in the postprocessing?
> > ![Screenshot from 2024-07-08 16-34-47](https://private-user-images.githubusercontent.com/95371554/346606093-30d49fed-0424-4232-91b6-819b442373c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTAwNjAsIm5iZiI6MTcyMDQ0OTc2MCwicGF0aCI6Ii85NTM3MTU1NC8zNDY2MDYwOTMtMzBkNDlmZWQtMDQyNC00MjMyLTkxYjYtODE5YjQ0MjM3M2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE0NDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTE5MmI4ZjcyMzEyNGQ2MzhhZTUzZTdhMmFjZjM5NmUwMmE0MmNhNTAyYWYyY2Y2ZWQ1Y2RhMGMzZDBhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IeeqDf6HO_eYLu8DdCTNnKRZM3GI0UI_e63VEtxR8FM)
> 
> Can you tell me the mesurement file? It could be that it is actually correct, but in that case the contacts are not ohmic and the measurement might be not reliable.

the file is 21-032-G_Hall-RT.txt

**Comment by anfiedler** [comment]
> > > @anfiedler is this voltage measurement correct? Or is it some error in the postprocessing?
> > > ![Screenshot from 2024-07-08 16-34-47](https://private-user-images.githubusercontent.com/95371554/346606093-30d49fed-0424-4232-91b6-819b442373c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTAwNjAsIm5iZiI6MTcyMDQ0OTc2MCwicGF0aCI6Ii85NTM3MTU1NC8zNDY2MDYwOTMtMzBkNDlmZWQtMDQyNC00MjMyLTkxYjYtODE5YjQ0MjM3M2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE0NDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTE5MmI4ZjcyMzEyNGQ2MzhhZTUzZTdhMmFjZjM5NmUwMmE0MmNhNTAyYWYyY2Y2ZWQ1Y2RhMGMzZDBhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IeeqDf6HO_eYLu8DdCTNnKRZM3GI0UI_e63VEtxR8FM)
> > 
> > 
> > Can you tell me the mesurement file? It could be that it is actually correct, but in that case the contacts are not ohmic and the measurement might be not reliable.
> 
> the file is 21-032-G_Hall-RT.txt

the upload is correct. the contacts are terrible, hence the measurement only gives tentative results. That is why it is important to always plot those graphys, too. The linear fit doesn't make sense here either. Everything is correct from NOMAD site.

**Comment by andreaa93** [comment]
okay, thanks
